"""Add default_wallet_id to users table

Revision ID: 10634eba643d
Revises: 490f3f5b32c3
Create Date: 2026-04-22 00:54:53.476002

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10634eba643d'
down_revision: Union[str, Sequence[str], None] = '490f3f5b32c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_recognition_jobs', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('PENDING', 'PROCESSING', 'DONE', 'FAILED', name='recognitionstatus'),
               existing_nullable=False)
        batch_op.create_index(batch_op.f('ix_ai_recognition_jobs_id'), ['id'], unique=False)

    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_api_keys_id'), ['id'], unique=False)
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_default', sa.Boolean(), nullable=True))
        batch_op.alter_column('category_type',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('EXPENSE', 'INCOME', name='categorytype'),
               existing_nullable=False)
        batch_op.create_index(batch_op.f('ix_categories_id'), ['id'], unique=False)
        batch_op.drop_column('color')

    with op.batch_alter_table('records', schema=None) as batch_op:
        batch_op.alter_column('record_type',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('EXPENSE', 'INCOME', name='recordtype'),
               existing_nullable=False)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('CONFIRMED', 'PENDING', 'REJECTED', name='recordstatus'),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_records_id'), ['id'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('default_wallet_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    with op.batch_alter_table('wallets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('currency', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
        batch_op.alter_column('wallet_type',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('BANK_CARD', 'E_WALLET', 'CASH', 'OTHER', name='wallettype'),
               nullable=True)
        batch_op.alter_column('balance',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_wallets_id'), ['id'], unique=False)
        batch_op.drop_column('color')
        batch_op.drop_column('icon')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wallets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('icon', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('color', sa.VARCHAR(length=20), nullable=True))
        batch_op.drop_index(batch_op.f('ix_wallets_id'))
        batch_op.alter_column('balance',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('wallet_type',
               existing_type=sa.Enum('BANK_CARD', 'E_WALLET', 'CASH', 'OTHER', name='wallettype'),
               type_=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('currency')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.drop_column('default_wallet_id')

    with op.batch_alter_table('records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_records_id'))
        batch_op.alter_column('status',
               existing_type=sa.Enum('CONFIRMED', 'PENDING', 'REJECTED', name='recordstatus'),
               type_=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('record_type',
               existing_type=sa.Enum('EXPENSE', 'INCOME', name='recordtype'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('color', sa.VARCHAR(length=20), nullable=True))
        batch_op.drop_index(batch_op.f('ix_categories_id'))
        batch_op.alter_column('category_type',
               existing_type=sa.Enum('EXPENSE', 'INCOME', name='categorytype'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
        batch_op.drop_column('is_default')

    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_index(batch_op.f('ix_api_keys_id'))

    with op.batch_alter_table('ai_recognition_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_recognition_jobs_id'))
        batch_op.alter_column('status',
               existing_type=sa.Enum('PENDING', 'PROCESSING', 'DONE', 'FAILED', name='recognitionstatus'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)

    # ### end Alembic commands ###
